name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "25"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build --warning-mode all

      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp "build/libs/PolarUtilities-$(cat VERSION).jar" dist/

      - name: Upload plugin JAR
        uses: actions/upload-artifact@v7
        with:
          name: PolarUtilities
          path: dist/*.jar
